### ISSUE TITLE
Read error from pytables

### ISSUE THREAD

**Issue by supriyom083** [blaze/odo#292]
```python
import numpy as np 
import tables as tb 
ndim = 600 
h5file = tb.openFile('test.h5', mode='w', title="Test Array") 
root = h5file.root
h5file.createArray(root, "test", np.zeros((ndim,ndim), dtype=float))    
h5file.close() 
from  odo import odo
odo('pytables://test.h5::/root/test','postgresql://postgresql:root@127.0.0.1::gg')
```
```
    C:\Anaconda\lib\site-packages\odo\backends\pytables.pyc in possibly_create_table(filename, dtype)
if datapath not in f: 
if dtype is None:
    raise ValueError('dshape cannot be None and datapath not'  ' in file')
else:
    ValueError: dshape can not be None and datapath not in file.
```

I am facing this strange issue while trying to import data from pytables

**Comment by cpcloud** [comment]
@supriyom083 Thanks for the report! I got to the bottom of this and there are two things at play here.

1. The `'pytables://'` string wasn't being properly removed from the input URI, so that's an actual bug.
2. Shoving an array into a database doesn't make sense without the user providing the column names. This should raise a proper error message. I'll also add some documentation to the effect of "provide column names when shoving an array into a database table"

**Comment by cpcloud** [comment]
@supriyom083 Also, thanks for providing a small, reproducible example. That really helped in getting to the bottom of this very quickly.
