### ISSUE TITLE
Why is it called odo?

### ISSUE THREAD

**Issue by apnewberry** [blaze/odo#570]
What does the name mean?

**Comment by llllllllll** [comment]
Odo is the name of a character from Star Trek`[1]`. In Star Trek, Odo is a changeling, which is a species that can change their physical form at will. `odo` the library is designed to change the shape and storage of data like how Odo the character can change their own form.

`[1]`: https://en.wikipedia.org/wiki/Odo_(Star_Trek)

From a practical view, `odo` is short and unique so people will remember it. The `odo.odo` function in particular is very powerful and does many different things. It would be hard to give it a concrete name because it is a mix of `append` and `convert`, so just `odo` is more memorable as its own operation.
